#!/bin/bash

# Note Performer Downloader & Installer
# - finlayacourt

# Check for root
if [ `whoami` != 'root' ]
  then
    echo "You must be root to do this."
    exit
fi

# Download & install noteperformer
echo
echo 'Install Noteperformer [Y/n]'
read response
if [ $response != 'n' ]
  then
    echo
    echo 'Downloading...'
    curl http://www.noteperformer.com/DownloadNotePerformerTrial.php -L > /tmp/noteperformer.dmg
    echo '...done'
    echo
    echo 'Installing...'
    hdiutil attach /tmp/noteperformer.dmg
    installer -package /Volumes/NotePerformer*/*.pkg -target /
    hdiutil detach /Volumes/NotePerformer*
    rm /tmp/noteperformer.dmg
    echo '...done'
fi

# Install libfaketime to Sibelius
echo
echo 'Patch for unlimited trial [Y/n]'
read response
echo
if [ $response != 'n' ]
  then
    # Try and find sibelius
    echo 'Finding Sibleius...'
    sibeliusLocations=()
    while IFS=  read -r -d $'\0'; do
        sibeliusLocations+=("$REPLY")
    done < <(find /Applications -iname "Sibelius*.app" -maxdepth 1 -print0)
    numberSibelius=${#sibeliusLocations[@]}

    # Ask for user help
    while true; do
      if (($numberSibelius == 0))
        then
          echo
          echo "Cannot find Sibelius. Input manually:"
          read sibeliusLocation
          if [ -f "${sibeliusLocation}/Contents/MacOS/Sibelius" ]
            then
              echo "...done"
              break
            else
              echo "No file at ${sibeliusLocation}/Contents/MacOS/Sibelius"
              echo
          fi
      elif (($numberSibelius > 1))
        then
          echo
          echo "Found $numberSibelius Sibelius Applications."
          for ((i=0;i<$numberSibelius;i++)); do
            echo "$i. ${sibeliusLocations[i]}"
          done
          echo "Select which:"
          read i
          sibeliusLocation=${sibeliusLocations[i]}
          echo
          echo '...done'
          break
      else
        sibeliusLocation=${sibeliusLocations[0]}
        echo '...done'
        break
      fi
    done
    
    # Install to patch Sibelius
    echo
    echo 'Installing patch...'
    curl https://raw.githubusercontent.com/finlayacourt/noteperformer-installer/master/libfaketime.1.dylib > ${sibeliusLocation}/Contents/Frameworks/libfaketime.1.dylib
    /usr/libexec/PlistBuddy -c 'Add :LSEnvironment:DYLD_INSERT_LIBRARIES string ${sibeliusLocation}/Contents/Frameworks/libfaketime.1.dylib' -c 'Add :LSEnvironment:FAKETIME string @2018-01-01 00:00:00' -c 'Add :LSEnvironment:DYLD_FORCE_FLAT_NAMESPACE string 1' '/Applications/Sibelius.app/Contents/Info.plist'
    echo '...done'
    echo
    echo 'Cleaning up...'
    /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -v -f ${sibeliusLocation}
    echo '...done'
    echo 
    echo 'Do you want to run Sibelius to test? [Y/n]'
    read response
    if [ $response != 'n' ]
      then
        open ${sibeliusLocation}
    fi
fi
exit
